# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"CU": "00_core.ipynb",
         "urlrequest": "01_helper.ipynb",
         "updatescore": "01_helper.ipynb",
         "shiftstartandduedate": "01_helper.ipynb",
         "updatepriority": "01_helper.ipynb"}

modules = ["core.py",
           "helper.py"]

doc_url = "https://StevedeP.github.io/ClickUpShiftScore/"

git_url = "https://github.com/StevedeP/ClickUpShiftScore/blob/master/ClickUpShiftScore"

def custom_doc_links(name): return None
